/**
 * /sys/skills.h
 */

#ifndef __SKILLS_H__
#define __SKILLS_H__

#include <gremios.h>        //definiciones de GC_XXXXX

#define HAB_TIEMPO_OLVIDA    21600

// bonificadores para habilidades según gremios:
#define BONUS_GUERREROS_IDENTIFICAR    10
#define BONUS_AVENTUREROS_IDENTIFICAR  5
#define BONUS_HERREROS_IDENTIFICAR     20
#define BONUS_GUERREROS_ATISBAR    5
#define BONUS_AVENTUREROS_ATISBAR  10
#define BONUS_AVENTUREROS_LENYA  10
#define BONUS_ARTESANOS_LENYA  5
#define BONUS_AVENTUREROS_ARBOLES  5

#define SK_RESULT_PIFIA         -1
#define SK_RESULT_FALLO          0
#define SK_RESULT_ACIERTO        1
#define SK_RESULT_ESPECIAL       2
#define SK_RESULT_CRITICO        3

/* ===================== */
/* HABILIDADES GENERALES */
/* ===================== */

#define HAB_LANZAR      "lanzar"
#define HAB_TREPAR      "trepar"
#define HAB_NADAR       "nadar"
#define HAB_SALTAR      "saltar"
#define HAB_COCINAR     "cocinar"
#define HAB_RASTREAR    "rastrear"
#define HAB_ROBAR       "robar"
#define HAB_COMERCIAR   "comerciar"
#define HAB_COMPARAR    "comparar"
#define HAB_FIRE        "encender fuego"
#define HAB_PESCAR      "pescar"
#define HAB_ESCALAR     "escalar"
#define HAB_IDVETAS     "identificar vetas"  // para enanos y herreros.
#define HAB_ESQUILAR    "esquilar lana"   // para algunos gremios como los artesanales, aventureros o similares.
#define HAB_DESOLLAR    "desollar animales"  // gremios artesanales y otros compativles.
#define HAB_DESCUARTIZAR "descuartizar"  // no lo tengo muy claro
#define HAB_TALAR       "talar árboles"  // gremios artesanales como carpintero o similares.
#define HAB_MADERA "cortar madera"  // artesanos y según que otros gremios o razas.
#define HAB_TALLAR      "tallar madera"  // artesanos carpinteros sobre todo
#define HAB_LEÑA "buscar leña" //generica nivel bajo, artesanos alto y aventureros medio.
#define HAB_ARBOLES   "localizar árboles"  //según gremios.
#define HAB_HOGUERAS "preparar hogueras" // según gremios nivel medio
#define HAB_ATISBAR     "atisbar" // genérica nivel bajo, según gremios nivel alto.

/* ====================== */
/* HABILIDADES DE COMBATE */
/* ====================== */
//nuevas para endor
#define HAB_DAGA        "pelea con daga" // antes era pelea con cuchillo.
#define HAB_GARROTE     "pelea con garrote"
#define HAB_CIMITARRA   "combate con cimitarra"
#define HAB_ESPADA_CORTA "lucha con espada corta"
#define HAB_MANDOBLE    "combate con mandoble" // 2 manos
#define HAB_CAYADO      "lucha con cayado"
#define HAB_JABALINA    "lucha con jabalina"
#define HAB_PICA        "combate con pica"
#define HAB_CIMITARRA_PESADA "combate con cimitarra pesada"  //2 manos
#define HAB_MAZA_PESADA "combate con maza pesada"  // 2 manos
#define HAB_MARTILLO    "combate con martillo"
#define HAB_MARTILLO_PESADO  "combate con martillo pesado"  //2 manos
#define HAB_HACHA_PESADA "combate con hacha pesada"   //2 manos
#define HAB_HACHA_KHAZAD "combate con hacha khazad"  // 2 manos
#define HAB_MANGUAL_PESADO "combate con mangual pesado"  // 2 manos
#define HAB_ESPADA_SINDA "lucha con espada sinda"
#define HAB_PICO        "combate con pico" // pico 2 manos, picoleta 1 mano.
#define HAB_AZADON      "combate con azadón de guerra"  // 2 manos
#define HAB_ESPADA_MEDIANA  "lucha con espada mediana"
#define HAB_IMPROVISADA  "pelea con arma improvisada"
// antiguas de simauria.
#define HAB_CUCHILLO    "pelea con cuchillo"
#define HAB_ALABARDA    "pelea con alabarda"   // usage of infantry-weapons
#define HAB_HACHA       "combate con hacha"      //antes pelea con hacha
#define HAB_CADENA      "pelea con cadena"     // usage of chain-weapons
#define HAB_MAZA        "combate con maza"       //antes pelea con maza
#define HAB_LANZA       "combate con lanza"      //antes pelea con lanza
#define HAB_VARA        "pelea con varas"      // usage of staffes
#define HAB_LATIGO      "pelea con látigo"    //antes pelea con latigos
#define HAB_MANGUAL     "lucha con mangual"    // usage of flails
#define HAB_ESGRIMA     "esgrima"              // usage of certain swords
#define HAB_ESPADA      "combate con espada"     // antes lucha con espada

#define HAB_SINARMAS    "lucha sin armas"  // antes era artes marciales
#define HAB_MANOPLA     "pelea con guantelete"    // antes pelea con manoplas
#define HAB_GUANTELETE  HAB_MANOPLA

#define HAB_ARCO        "tiro con arco"

#define HAB_EXPERTISE   "experto en combate"
#define HAB_REFLEXES    "reflejos de combate"
#define HAB_GUERRERO    "guerrero verdadero"

#define HAB_ESQUIVAR    "esquivar ataque"    //esquiva
#ifndef HAB_PARADA
#define HAB_PARADA      "parada"        // parada con arma
#endif
#define HAB_ESCUDO      "bloqueo con escudo"
#define HAB_TAICHI      "taichi" //parry sin armas

#define HAB_CRITICO     "golpe critico"  // do a critical hit          Cri
#define HAB_MASDANYO    "aumentar daño"
#define HAB_ZEN         "zen" //enhanced damage sin armas

#define HAB_ODIO        "odio"
#define HAB_BARBARO     "alarido del barbaro"  // Stun/Scare someone

#define HAB_XARMAS      "lucha con multiples armas"    //two or multi weapon fighting
#define HAB_NATURAL     "ataques naturales"    // Esta habilidad se usa para ver que
    // tal atacas con tus ataques naturales extras y SOLO extras, sera
    // usada ADEMAS de la hab del ataque correspondiente
    //(no de la misma forma)

#define HAB_ACUCHILLAR  "acuchillar"
#define HAB_CUTTHROAT   "cortar gargantas"
#define HAB_FINTAR      "fintar"
#define HAB_FINTA_MEJORADA  "finta mejorada"
#define HAB_STUN        "inmovilizar"
#define HAB_ZANCADILLEAR "zancadillear"  // nueva para aventureros, como inmobilizar.
#define HAB_COMBATE_BASICO ({ HAB_DAGA, HAB_ALABARDA, HAB_HACHA, HAB_CADENA,\
        HAB_MAZA,HAB_LANZA, HAB_VARA, HAB_LATIGO, HAB_MANGUAL,\
        HAB_ESGRIMA, HAB_ESPADA, HAB_SINARMAS, HAB_MANOPLA, HAB_CUCHILLO, HAB_GARROTE, \
        HAB_CIMITARRA, HAB_ESPADA_CORTA, HAB_MANDOBLE \
                 })
#define HAB_COMBATE_AVANZADO ({ HAB_PARADA, HAB_ESQUIVAR, HAB_ESCUDO, \
        /*HAB_TAICHI,*/ HAB_EXPERTISE, HAB_REFLEXES, \
                  })
#define HAB_COMBATE_EXPERTO ({ HAB_MASDANYO, HAB_ZEN })
#define HAB_COMBATE_WARRIOR ({ HAB_GUERRERO, HAB_CRITICO })

/* =================== */
/* HABILIDADES MAGICAS */
/* =================== */
#define HAB_MEMORIZAR   "memorizar"
#define HAB_RUNAS       "leer runas"
#define HAB_ABSORCION   "absorción de hechizos"
#define HAB_REFLEXION   "reflexión de hechizos"
#define HAB_RESMAGIA    "resistencia mágica"
#define HAB_ARMASMAGIC  "pelea con armas mágicas"
#define HAB_CONCENTRAR  "concentración"
#define HAB_MEDITACION  "meditacion"
#define HAB_ESCRIBIR_RUNAS "escribir runas"

/* ======================= */
/* HABILIDADES MISCELANEAS */
/* ======================= */
#define HAB_BALSAMO     "aplicar bálsamo"
#define HAB_DO_BALSAMO  "preparar bálsamo"
#define HAB_IDENTIFICAR "identificar armas"          //antes solo identificar.  identify armours and weapons
#define HAB_INSPECCIONAR "inspeccionar atavíos"
#define HAB_REPARAR     "reparar"              // repair armours and weapons
#define HAB_VENDAJE     "vendaje"        // bandage someone            Ban
#define HAB_ESCONDERSE  "esconderse"
#define HAB_OCULTARSE   HAB_ESCONDERSE
#define HAB_IDPLANTAS   "reconocer plantas"
#define HAB_SIGILO      "sigilo"
#define HAB_ENGANYAR    "engaño"
#define HAB_DO_VENENO   "preparar venenos"
#define HAB_ENVENENAR   "envenenar"

/* =========================================== */
/* LISTAS DE HABILIDADES GENERALES Y DE GREMIO */
/* =========================================== */

//#define HAB_GENERALES    ({HAB_LANZAR,HAB_TREPAR,HAB_NADAR,HAB_SALTAR,HAB_RASTREAR \
                          //,HAB_COCINAR,HAB_ROBAR,HAB_COMERCIAR,HAB_COMPARAR, HAB_FIRE})
#define HAB_GENERALES    ({HAB_LANZAR,HAB_TREPAR,HAB_SALTAR, HAB_COMPARAR,\
                          HAB_FIRE, HAB_HOGUERAS, HAB_ATISBAR, HAB_LEÑA})


//Nyh al ataquer!!!:
//
// NIV_ nivel a partir del que puedes aprender la habilidad
// MAX_ máximo al que puedes llegar
// GRA_ gratis: 1 si es gratis, 0 si no lo es
#define HAB_GRATIS      1
#define HAB_NO_GRATIS   0

//*********************||
// HABILIDADES KISALAS ||
//*********************||
#define NIV_VARA_KISALAS        1
#define NIV_CUCHILLO_KISALAS    1
#define NIV_LANZA_KISALAS       1
#define NIV_LANZAR_KISALAS      1
#define NIV_ESQUIVAR_KISALAS    5
#define NIV_IDPLANTAS_KISALAS   8
#define NIV_ODIO_KISALAS        10
#define NIV_BALSAMO_KISALAS     12
#define NIV_DO_BALSAMO_KISALAS  12
#define NIV_REFLEXES_KISALAS    15
#define NIV_MASDANYO_KISALAS    17
#define NIV_PARADA_KISALAS      20
#define NIV_ARCO_KISALAS        25
#define NIV_EXPERTISE_KISALAS   30

#define MAX_VARA_KISALAS        100
#define MAX_CUCHILLO_KISALAS    100
#define MAX_LANZA_KISALAS       100
#define MAX_LANZAR_KISALAS      100
#define MAX_ESQUIVAR_KISALAS    100
#define MAX_IDPLANTAS_KISALAS   100
#define MAX_ODIO_KISALAS        100
#define MAX_BALSAMO_KISALAS     100
#define MAX_DO_BALSAMO_KISALAS  100
#define MAX_REFLEXES_KISALAS    100
#define MAX_MASDANYO_KISALAS    100
#define MAX_PARADA_KISALAS      100
#define MAX_ARCO_KISALAS        100
#define MAX_EXPERTISE_KISALAS   100

#define GRA_VARA_KISALAS        HAB_GRATIS
#define GRA_CUCHILLO_KISALAS    HAB_GRATIS
#define GRA_LANZA_KISALAS       HAB_GRATIS
#define GRA_LANZAR_KISALAS      HAB_GRATIS
#define GRA_ESQUIVAR_KISALAS    HAB_GRATIS
#define GRA_IDPLANTAS_KISALAS   HAB_GRATIS
#define GRA_ODIO_KISALAS        HAB_GRATIS
#define GRA_BALSAMO_KISALAS     HAB_GRATIS
#define GRA_DO_BALSAMO_KISALAS  HAB_GRATIS
#define GRA_REFLEXES_KISALAS    HAB_GRATIS
#define GRA_MASDANYO_KISALAS    HAB_GRATIS
#define GRA_PARADA_KISALAS      HAB_GRATIS
#define GRA_ARCO_KISALAS        HAB_GRATIS
#define GRA_EXPERTISE_KISALAS   HAB_GRATIS

#define HAB_KISALAS  ({ HAB_VARA, HAB_CUCHILLO, HAB_LANZA,\
            HAB_ESQUIVAR, HAB_LANZAR, \
            HAB_ODIO, HAB_ARCO, HAB_BALSAMO, HAB_DO_BALSAMO, HAB_IDPLANTAS, \
            HAB_PARADA, HAB_EXPERTISE, HAB_REFLEXES,\
            HAB_MASDANYO })
#define NIV_KISALAS  ({ NIV_VARA_KISALAS, NIV_CUCHILLO_KISALAS, NIV_LANZA_KISALAS, \
            NIV_ESQUIVAR_KISALAS, NIV_LANZAR_KISALAS, \
            NIV_ODIO_KISALAS, NIV_ARCO_KISALAS, NIV_BALSAMO_KISALAS, NIV_DO_BALSAMO_KISALAS, NIV_IDPLANTAS_KISALAS, \
            NIV_PARADA_KISALAS, NIV_EXPERTISE_KISALAS, NIV_REFLEXES_KISALAS,\
            NIV_MASDANYO_KISALAS })
#define MAX_KISALAS  ({ MAX_VARA_KISALAS, MAX_CUCHILLO_KISALAS, MAX_LANZA_KISALAS, \
            MAX_ESQUIVAR_KISALAS, MAX_LANZAR_KISALAS, \
            MAX_ODIO_KISALAS, MAX_ARCO_KISALAS, MAX_BALSAMO_KISALAS, MAX_DO_BALSAMO_KISALAS, MAX_IDPLANTAS_KISALAS, \
            MAX_PARADA_KISALAS, MAX_EXPERTISE_KISALAS, MAX_REFLEXES_KISALAS,\
            MAX_MASDANYO_KISALAS })
#define GRA_KISALAS  ({ GRA_VARA_KISALAS, GRA_CUCHILLO_KISALAS, GRA_LANZA_KISALAS, \
            GRA_ESQUIVAR_KISALAS, GRA_LANZAR_KISALAS, \
            GRA_ODIO_KISALAS, GRA_ARCO_KISALAS, GRA_BALSAMO_KISALAS, GRA_DO_BALSAMO_KISALAS, GRA_IDPLANTAS_KISALAS, \
            GRA_PARADA_KISALAS, GRA_EXPERTISE_KISALAS, GRA_REFLEXES_KISALAS,\
            GRA_MASDANYO_KISALAS })

//**************************||
// HABILIDADES CONJURADORES ||
//**************************||
#define NIV_VARA_CONJURADORES       1
#define NIV_CUCHILLO_CONJURADORES   1
#define NIV_MEMORIZAR_CONJURADORES  1
#define NIV_RUNAS_CONJURADORES      1

#define MAX_VARA_CONJURADORES       100
#define MAX_CUCHILLO_CONJURADORES   100
#define MAX_MEMORIZAR_CONJURADORES  100
#define MAX_RUNAS_CONJURADORES      100

#define GRA_VARA_CONJURADORES       HAB_GRATIS
#define GRA_CUCHILLO_CONJURADORES   HAB_GRATIS
#define GRA_MEMORIZAR_CONJURADORES  HAB_GRATIS
#define GRA_RUNAS_CONJURADORES      HAB_GRATIS

#define HAB_CONJURADORES ({ HAB_VARA, HAB_CUCHILLO, HAB_MEMORIZAR, HAB_RUNAS})
#define NIV_CONJURADORES ({ NIV_VARA_CONJURADORES, NIV_CUCHILLO_CONJURADORES, \
                NIV_MEMORIZAR_CONJURADORES, NIV_RUNAS_CONJURADORES})
#define MAX_CONJURADORES ({ MAX_VARA_CONJURADORES, MAX_CUCHILLO_CONJURADORES,\
                MAX_MEMORIZAR_CONJURADORES, MAX_RUNAS_CONJURADORES})
#define GRA_CONJURADORES ({ GRA_VARA_CONJURADORES, GRA_CUCHILLO_CONJURADORES,\
                GRA_MEMORIZAR_CONJURADORES, GRA_RUNAS_CONJURADORES})

//************************||
// HABILIDADES HECHICEROS ||
//************************||
#define NIV_VARA_HECHICEROS         10
#define NIV_CUCHILLO_HECHICEROS     10
#define NIV_MEMORIZAR_HECHICEROS    1
#define NIV_RUNAS_HECHICEROS        8
#define NIV_CONCENTRAR_HECHICEROS   12
#define NIV_ARMASMAGIC_HECHICEROS   25
#define NIV_RESMAGIA_HECHICEROS     30
#define NIV_REFLEXION_HECHICEROS    35
#define NIV_ABSORCION_HECHICEROS    40

#define MAX_VARA_HECHICEROS         100
#define MAX_CUCHILLO_HECHICEROS     100
#define MAX_MEMORIZAR_HECHICEROS    100
#define MAX_RUNAS_HECHICEROS        100
#define MAX_CONCENTRAR_HECHICEROS   100
#define MAX_ARMASMAGIC_HECHICEROS   100
#define MAX_RESMAGIA_HECHICEROS     100
#define MAX_REFLEXION_HECHICEROS    100
#define MAX_ABSORCION_HECHICEROS    100

#define GRA_VARA_HECHICEROS         HAB_GRATIS
#define GRA_CUCHILLO_HECHICEROS     HAB_GRATIS
#define GRA_MEMORIZAR_HECHICEROS    HAB_GRATIS
#define GRA_RUNAS_HECHICEROS        HAB_GRATIS
#define GRA_CONCENTRAR_HECHICEROS   HAB_GRATIS
#define GRA_ARMASMAGIC_HECHICEROS   HAB_GRATIS
#define GRA_RESMAGIA_HECHICEROS     HAB_GRATIS
#define GRA_REFLEXION_HECHICEROS    HAB_GRATIS
#define GRA_ABSORCION_HECHICEROS    HAB_GRATIS

#define HAB_HECHICEROS   ({ HAB_VARA, HAB_CUCHILLO, HAB_ABSORCION, HAB_REFLEXION, HAB_RESMAGIA,\
                            HAB_ARMASMAGIC, HAB_CONCENTRAR, HAB_RUNAS,\
                            HAB_MEMORIZAR })
#define NIV_HECHICEROS   ({ NIV_VARA_HECHICEROS, NIV_CUCHILLO_HECHICEROS, \
                NIV_ABSORCION_HECHICEROS, NIV_REFLEXION_HECHICEROS, NIV_RESMAGIA_HECHICEROS,\
                            NIV_ARMASMAGIC_HECHICEROS, NIV_CONCENTRAR_HECHICEROS, NIV_RUNAS_HECHICEROS,\
                            NIV_MEMORIZAR_HECHICEROS })
#define MAX_HECHICEROS   ({ MAX_VARA_HECHICEROS, MAX_CUCHILLO_HECHICEROS, \
                MAX_ABSORCION_HECHICEROS, MAX_REFLEXION_HECHICEROS, MAX_RESMAGIA_HECHICEROS,\
                            MAX_ARMASMAGIC_HECHICEROS, MAX_CONCENTRAR_HECHICEROS, MAX_RUNAS_HECHICEROS,\
                            MAX_MEMORIZAR_HECHICEROS })
#define GRA_HECHICEROS   ({ GRA_VARA_HECHICEROS, GRA_CUCHILLO_HECHICEROS, \
                GRA_ABSORCION_HECHICEROS, GRA_REFLEXION_HECHICEROS, GRA_RESMAGIA_HECHICEROS,\
                            GRA_ARMASMAGIC_HECHICEROS, GRA_CONCENTRAR_HECHICEROS, GRA_RUNAS_HECHICEROS,\
                            GRA_MEMORIZAR_HECHICEROS })

//***********************||
// HABILIDADES GUERREROS ||
//***********************||
#define NIV_VARA_GUERREROS          1
#define NIV_CUCHILLO_GUERREROS      1
#define NIV_LANZA_GUERREROS         1
#define NIV_ALABARDA_GUERREROS      1
#define NIV_HACHA_GUERREROS         1
#define NIV_CADENA_GUERREROS        1
#define NIV_MAZA_GUERREROS          1
#define NIV_LATIGO_GUERREROS        1
#define NIV_MANGUAL_GUERREROS       1
#define NIV_ESGRIMA_GUERREROS       1 // la sustituyo por la de improvisada para probar
#define NIV_IMPROVISADA_GUERREROS 1
#define NIV_ESPADA_GUERREROS        1
#define NIV_MANOPLA_GUERREROS       1
#define NIV_SINARMAS_GUERREROS      1
#define NIV_IDENTIFICAR_GUERREROS   1
#define NIV_DAGA_GUERREROS   1
#define NIV_CIMITARRA_GUERREROS   1
#define NIV_ESPADA_CORTA_GUERREROS   1
#define NIV_MANDOBLE_GUERREROS   1
#define NIV_ESCUDO_GUERREROS        5
#define NIV_REPARAR_GUERREROS       6 //10, 25
#define NIV_VENDAJE_GUERREROS       8
#define NIV_EXPERTISE_GUERREROS     10
#define NIV_PARADA_GUERREROS        12
#define NIV_MASDANYO_GUERREROS      16
#define NIV_ESQUIVAR_GUERREROS      18
#define NIV_REFLEXES_GUERREROS      20
#define NIV_XARMAS_GUERREROS        25
#define NIV_GUERRERO_GUERREROS      30
#define NIV_BARBARO_GUERREROS       35
#define NIV_CRITICO_GUERREROS       45

#define MAX_VARA_GUERREROS          100
#define MAX_CUCHILLO_GUERREROS      100
#define MAX_LANZA_GUERREROS         100
#define MAX_ALABARDA_GUERREROS      100
#define MAX_HACHA_GUERREROS         100
#define MAX_CADENA_GUERREROS        100
#define MAX_MAZA_GUERREROS          100
#define MAX_LATIGO_GUERREROS        100
#define MAX_MANGUAL_GUERREROS       100
#define MAX_ESGRIMA_GUERREROS       100
#define MAX_IMPROVISADA_GUERREROS 100
#define MAX_ESPADA_GUERREROS        100
#define MAX_MANOPLA_GUERREROS       100
#define MAX_SINARMAS_GUERREROS      100
#define MAX_IDENTIFICAR_GUERREROS   100
#define MAX_DAGA_GUERREROS   100
#define MAX_CIMITARRA_GUERREROS   100
#define MAX_ESPADA_CORTA_GUERREROS   100
#define MAX_MANDOBLE_GUERREROS   100
#define MAX_ESCUDO_GUERREROS        100
#define MAX_REPARAR_GUERREROS       100
#define MAX_VENDAJE_GUERREROS       100
#define MAX_EXPERTISE_GUERREROS     100
#define MAX_PARADA_GUERREROS        100
#define MAX_MASDANYO_GUERREROS      100
#define MAX_ESQUIVAR_GUERREROS      100
#define MAX_REFLEXES_GUERREROS      100
#define MAX_XARMAS_GUERREROS        100
#define MAX_GUERRERO_GUERREROS      100
#define MAX_BARBARO_GUERREROS       100
#define MAX_CRITICO_GUERREROS       100

#define GRA_VARA_GUERREROS          HAB_GRATIS
#define GRA_CUCHILLO_GUERREROS      HAB_GRATIS
#define GRA_LANZA_GUERREROS         HAB_GRATIS
#define GRA_ALABARDA_GUERREROS      HAB_GRATIS
#define GRA_HACHA_GUERREROS         HAB_GRATIS
#define GRA_CADENA_GUERREROS        HAB_GRATIS
#define GRA_MAZA_GUERREROS          HAB_GRATIS
#define GRA_LATIGO_GUERREROS        HAB_GRATIS
#define GRA_MANGUAL_GUERREROS       HAB_GRATIS
#define GRA_ESGRIMA_GUERREROS       HAB_GRATIS
#define GRA_IMPROVISADA_GUERREROS       HAB_GRATIS
#define GRA_ESPADA_GUERREROS        HAB_GRATIS
#define GRA_MANOPLA_GUERREROS       HAB_GRATIS
#define GRA_SINARMAS_GUERREROS      HAB_GRATIS
#define GRA_IDENTIFICAR_GUERREROS   HAB_GRATIS
#define GRA_DAGA_GUERREROS   HAB_GRATIS
#define GRA_CIMITARRA_GUERREROS   HAB_GRATIS
#define GRA_ESPADA_CORTA_GUERREROS   HAB_GRATIS
#define GRA_MANDOBLE_GUERREROS   HAB_GRATIS
#define GRA_ESCUDO_GUERREROS        HAB_GRATIS
#define GRA_REPARAR_GUERREROS       HAB_GRATIS
#define GRA_VENDAJE_GUERREROS       HAB_GRATIS
#define GRA_EXPERTISE_GUERREROS     HAB_GRATIS
#define GRA_PARADA_GUERREROS        HAB_GRATIS
#define GRA_MASDANYO_GUERREROS      HAB_GRATIS
#define GRA_ESQUIVAR_GUERREROS      HAB_GRATIS
#define GRA_REFLEXES_GUERREROS      HAB_GRATIS
#define GRA_XARMAS_GUERREROS        HAB_GRATIS
#define GRA_GUERRERO_GUERREROS      HAB_GRATIS
#define GRA_BARBARO_GUERREROS       HAB_GRATIS
#define GRA_CRITICO_GUERREROS       HAB_GRATIS

#define HAB_GUERREROS    ({ HAB_VARA, HAB_CUCHILLO, HAB_LANZA, \
               HAB_ALABARDA, HAB_HACHA, HAB_CADENA, HAB_MAZA, \
               HAB_LATIGO, HAB_MANGUAL, HAB_IMPROVISADA, HAB_ESPADA, \
               HAB_MANOPLA, HAB_SINARMAS, \
               HAB_BARBARO, HAB_IDENTIFICAR,HAB_DAGA, HAB_CIMITARRA, HAB_ESPADA_CORTA, HAB_MANDOBLE, \
               HAB_REPARAR, HAB_VENDAJE, HAB_CRITICO, HAB_PARADA, \
               HAB_ESCUDO, HAB_EXPERTISE, HAB_MASDANYO, \
               HAB_ESQUIVAR, HAB_REFLEXES, HAB_GUERRERO, \
               HAB_XARMAS \
                           })
#define NIV_GUERREROS   ({ NIV_VARA_GUERREROS, NIV_CUCHILLO_GUERREROS, NIV_LANZA_GUERREROS, \
               NIV_ALABARDA_GUERREROS, NIV_HACHA_GUERREROS, NIV_CADENA_GUERREROS, NIV_MAZA_GUERREROS, \
               NIV_LATIGO_GUERREROS, NIV_MANGUAL_GUERREROS, NIV_IMPROVISADA_GUERREROS, NIV_ESPADA_GUERREROS, \
               NIV_MANOPLA_GUERREROS, NIV_SINARMAS_GUERREROS, \
               NIV_BARBARO_GUERREROS, NIV_IDENTIFICAR_GUERREROS, NIV_DAGA_GUERREROS, NIV_CIMITARRA_GUERREROS, NIV_ESPADA_CORTA_GUERREROS, NIV_MANDOBLE_GUERREROS,\
               NIV_REPARAR_GUERREROS, NIV_VENDAJE_GUERREROS, NIV_CRITICO_GUERREROS, NIV_PARADA_GUERREROS, \
               NIV_ESCUDO_GUERREROS, NIV_EXPERTISE_GUERREROS, NIV_MASDANYO_GUERREROS, \
               NIV_ESQUIVAR_GUERREROS, NIV_REFLEXES_GUERREROS, NIV_GUERRERO_GUERREROS, \
               NIV_XARMAS_GUERREROS \
                           })
#define MAX_GUERREROS   ({ MAX_VARA_GUERREROS, MAX_CUCHILLO_GUERREROS, MAX_LANZA_GUERREROS, \
               MAX_ALABARDA_GUERREROS, MAX_HACHA_GUERREROS, MAX_CADENA_GUERREROS, MAX_MAZA_GUERREROS, \
               MAX_LATIGO_GUERREROS, MAX_MANGUAL_GUERREROS, MAX_IMPROVISADA_GUERREROS, MAX_ESPADA_GUERREROS, \
               MAX_MANOPLA_GUERREROS, MAX_SINARMAS_GUERREROS, \
               MAX_BARBARO_GUERREROS, MAX_IDENTIFICAR_GUERREROS, MAX_DAGA_GUERREROS, MAX_CIMITARRA_GUERREROS, MAX_ESPADA_CORTA_GUERREROS, MAX_MANDOBLE_GUERREROS,\
               MAX_REPARAR_GUERREROS, MAX_VENDAJE_GUERREROS, MAX_CRITICO_GUERREROS, MAX_PARADA_GUERREROS, \
               MAX_ESCUDO_GUERREROS, MAX_EXPERTISE_GUERREROS, MAX_MASDANYO_GUERREROS, \
               MAX_ESQUIVAR_GUERREROS, MAX_REFLEXES_GUERREROS, MAX_GUERRERO_GUERREROS, \
               MAX_XARMAS_GUERREROS \
                           })
#define GRA_GUERREROS   ({ GRA_VARA_GUERREROS, GRA_CUCHILLO_GUERREROS, GRA_LANZA_GUERREROS, \
               GRA_ALABARDA_GUERREROS, GRA_HACHA_GUERREROS, GRA_CADENA_GUERREROS, GRA_MAZA_GUERREROS, \
               GRA_LATIGO_GUERREROS, GRA_MANGUAL_GUERREROS, GRA_IMPROVISADA_GUERREROS, GRA_ESPADA_GUERREROS, \
               GRA_MANOPLA_GUERREROS, GRA_SINARMAS_GUERREROS, \
               GRA_BARBARO_GUERREROS, GRA_IDENTIFICAR_GUERREROS, GRA_DAGA_GUERREROS, GRA_CIMITARRA_GUERREROS, GRA_ESPADA_CORTA_GUERREROS, GRA_MANDOBLE_GUERREROS,\
               GRA_REPARAR_GUERREROS, GRA_VENDAJE_GUERREROS, GRA_CRITICO_GUERREROS, GRA_PARADA_GUERREROS, \
               GRA_ESCUDO_GUERREROS, GRA_EXPERTISE_GUERREROS, GRA_MASDANYO_GUERREROS, \
               GRA_ESQUIVAR_GUERREROS, GRA_REFLEXES_GUERREROS, GRA_GUERRERO_GUERREROS, \
               GRA_XARMAS_GUERREROS \
                           })

//***************************||
// HABILIDADES GUARDABOSQUES ||
//***************************||
#define NIV_VARA_GUARDABOSQUES          1
#define NIV_CUCHILLO_GUARDABOSQUES      1
#define NIV_LANZA_GUARDABOSQUES         1
#define NIV_ESPADA_GUARDABOSQUES        1
#define NIV_IDPLANTAS_GUARDABOSQUES     1
#define NIV_RASTREAR_GUARDABOSQUES      1
#define NIV_LANZAR_GUARDABOSQUES        3
#define NIV_ESCONDERSE_GUARDABOSQUES    5
#define NIV_ESQUIVAR_GUARDABOSQUES      7
#define NIV_XARMAS_GUARDABOSQUES        10
#define NIV_EXPERTISE_GUARDABOSQUES     13
#define NIV_PARADA_GUARDABOSQUES        15
#define NIV_MASDANYO_GUARDABOSQUES      18
#define NIV_ARCO_GUARDABOSQUES          20
#define NIV_BALSAMO_GUARDABOSQUES       12
#define NIV_DO_BALSAMO_GUARDABOSQUES    12
#define NIV_REFLEXES_GUARDABOSQUES      23

#define MAX_VARA_GUARDABOSQUES          100
#define MAX_CUCHILLO_GUARDABOSQUES      100
#define MAX_LANZA_GUARDABOSQUES         100
#define MAX_ESPADA_GUARDABOSQUES        100
#define MAX_IDPLANTAS_GUARDABOSQUES     100
#define MAX_LANZAR_GUARDABOSQUES        100
#define MAX_RASTREAR_GUARDABOSQUES      100
#define MAX_ESQUIVAR_GUARDABOSQUES      100
#define MAX_ESCONDERSE_GUARDABOSQUES    100
#define MAX_EXPERTISE_GUARDABOSQUES     100
#define MAX_PARADA_GUARDABOSQUES        100
#define MAX_MASDANYO_GUARDABOSQUES      100
#define MAX_ARCO_GUARDABOSQUES          100
#define MAX_BALSAMO_GUARDABOSQUES       100
#define MAX_DO_BALSAMO_GUARDABOSQUES    100
#define MAX_XARMAS_GUARDABOSQUES        100
#define MAX_REFLEXES_GUARDABOSQUES      100

#define GRA_VARA_GUARDABOSQUES          HAB_NO_GRATIS
#define GRA_CUCHILLO_GUARDABOSQUES      HAB_NO_GRATIS
#define GRA_LANZA_GUARDABOSQUES         HAB_NO_GRATIS
#define GRA_ESPADA_GUARDABOSQUES        HAB_NO_GRATIS
#define GRA_IDPLANTAS_GUARDABOSQUES     HAB_NO_GRATIS
#define GRA_LANZAR_GUARDABOSQUES        HAB_NO_GRATIS
#define GRA_RASTREAR_GUARDABOSQUES      HAB_NO_GRATIS
#define GRA_ESQUIVAR_GUARDABOSQUES      HAB_NO_GRATIS
#define GRA_ESCONDERSE_GUARDABOSQUES    HAB_NO_GRATIS
#define GRA_EXPERTISE_GUARDABOSQUES     HAB_NO_GRATIS
#define GRA_PARADA_GUARDABOSQUES        HAB_NO_GRATIS
#define GRA_MASDANYO_GUARDABOSQUES      HAB_NO_GRATIS
#define GRA_ARCO_GUARDABOSQUES          HAB_NO_GRATIS
#define GRA_BALSAMO_GUARDABOSQUES       HAB_NO_GRATIS
#define GRA_DO_BALSAMO_GUARDABOSQUES    HAB_NO_GRATIS
#define GRA_XARMAS_GUARDABOSQUES        HAB_NO_GRATIS
#define GRA_REFLEXES_GUARDABOSQUES      HAB_NO_GRATIS

#define HAB_GUARDABOSQUES ({HAB_VARA, HAB_CUCHILLO, HAB_LANZA, HAB_ESPADA, \
              HAB_LANZAR, HAB_ESCONDERSE, HAB_PARADA, \
              HAB_ESQUIVAR, HAB_RASTREAR, HAB_ARCO, HAB_BALSAMO, HAB_DO_BALSAMO, HAB_IDPLANTAS,\
              HAB_EXPERTISE, HAB_MASDANYO, \
              HAB_REFLEXES, HAB_XARMAS })
#define NIV_GUARDABOSQUES ({NIV_VARA_GUARDABOSQUES, NIV_CUCHILLO_GUARDABOSQUES, NIV_LANZA_GUARDABOSQUES, NIV_ESPADA_GUARDABOSQUES, \
              NIV_LANZAR_GUARDABOSQUES, NIV_ESCONDERSE_GUARDABOSQUES, NIV_PARADA_GUARDABOSQUES, \
              NIV_ESQUIVAR_GUARDABOSQUES, NIV_RASTREAR_GUARDABOSQUES, NIV_ARCO_GUARDABOSQUES, NIV_BALSAMO_GUARDABOSQUES, NIV_DO_BALSAMO_GUARDABOSQUES, NIV_IDPLANTAS_GUARDABOSQUES,\
              NIV_EXPERTISE_GUARDABOSQUES, NIV_MASDANYO_GUARDABOSQUES, \
              NIV_REFLEXES_GUARDABOSQUES, NIV_XARMAS_GUARDABOSQUES })
#define MAX_GUARDABOSQUES ({MAX_VARA_GUARDABOSQUES, MAX_CUCHILLO_GUARDABOSQUES, MAX_LANZA_GUARDABOSQUES, MAX_ESPADA_GUARDABOSQUES, \
              MAX_LANZAR_GUARDABOSQUES, MAX_ESCONDERSE_GUARDABOSQUES, MAX_PARADA_GUARDABOSQUES, \
              MAX_ESQUIVAR_GUARDABOSQUES, MAX_RASTREAR_GUARDABOSQUES, MAX_ARCO_GUARDABOSQUES, MAX_BALSAMO_GUARDABOSQUES, MAX_DO_BALSAMO_GUARDABOSQUES, MAX_IDPLANTAS_GUARDABOSQUES,\
              MAX_EXPERTISE_GUARDABOSQUES, MAX_MASDANYO_GUARDABOSQUES, \
              MAX_REFLEXES_GUARDABOSQUES, MAX_XARMAS_GUARDABOSQUES })
#define GRA_GUARDABOSQUES ({GRA_VARA_GUARDABOSQUES, GRA_CUCHILLO_GUARDABOSQUES, GRA_LANZA_GUARDABOSQUES, GRA_ESPADA_GUARDABOSQUES, \
              GRA_LANZAR_GUARDABOSQUES, GRA_ESCONDERSE_GUARDABOSQUES, GRA_PARADA_GUARDABOSQUES, \
              GRA_ESQUIVAR_GUARDABOSQUES, GRA_RASTREAR_GUARDABOSQUES, GRA_ARCO_GUARDABOSQUES, GRA_BALSAMO_GUARDABOSQUES, GRA_DO_BALSAMO_GUARDABOSQUES, GRA_IDPLANTAS_GUARDABOSQUES,\
              GRA_EXPERTISE_GUARDABOSQUES, GRA_MASDANYO_GUARDABOSQUES, \
              GRA_REFLEXES_GUARDABOSQUES, GRA_XARMAS_GUARDABOSQUES })

//**********************||
// HABILIDADES ASESINOS ||
//**********************||
#define NIV_CUCHILLO_ASESINOS       1
#define NIV_ESGRIMA_ASESINOS        1
#define NIV_ACUCHILLAR_ASESINOS     1
#define NIV_ESCONDERSE_ASESINOS     3
#define NIV_ESQUIVAR_ASESINOS       5
#define NIV_SIGILO_ASESINOS         8
#define NIV_XARMAS_ASESINOS         10
#define NIV_LANZAR_ASESINOS         12
#define NIV_EXPERTISE_ASESINOS      14
#define NIV_ENGANYAR_ASESINOS       16
#define NIV_MASDANYO_ASESINOS       18
#define NIV_FINTAR_ASESINOS         20
#define NIV_REFLEXES_ASESINOS       25
#define NIV_DO_VENENO_ASESINOS      30
#define NIV_ENVENENAR_ASESINOS      30
#define NIV_CUTTHROAT_ASESINOS      35
#define NIV_PARADA_ASESINOS         40
#define NIV_STUN_ASESINOS           45
#define NIV_FINTA_MEJORADA_ASESINOS 50

#define MAX_CUCHILLO_ASESINOS       100
#define MAX_ESGRIMA_ASESINOS        100
#define MAX_ACUCHILLAR_ASESINOS     100
#define MAX_ESCONDERSE_ASESINOS     100
#define MAX_ESQUIVAR_ASESINOS       100
#define MAX_SIGILO_ASESINOS         100
#define MAX_XARMAS_ASESINOS         100
#define MAX_LANZAR_ASESINOS         100
#define MAX_EXPERTISE_ASESINOS      100
#define MAX_ENGANYAR_ASESINOS       100
#define MAX_MASDANYO_ASESINOS       100
#define MAX_FINTAR_ASESINOS         100
#define MAX_REFLEXES_ASESINOS       100
#define MAX_DO_VENENO_ASESINOS      100
#define MAX_ENVENENAR_ASESINOS      100
#define MAX_CUTTHROAT_ASESINOS      100
#define MAX_PARADA_ASESINOS         100
#define MAX_STUN_ASESINOS           100
#define MAX_FINTA_MEJORADA_ASESINOS 100

#define GRA_CUCHILLO_ASESINOS       HAB_GRATIS
#define GRA_ESGRIMA_ASESINOS        HAB_GRATIS
#define GRA_ACUCHILLAR_ASESINOS     HAB_GRATIS
#define GRA_ESCONDERSE_ASESINOS     HAB_GRATIS
#define GRA_ESQUIVAR_ASESINOS       HAB_GRATIS
#define GRA_SIGILO_ASESINOS         HAB_GRATIS
#define GRA_XARMAS_ASESINOS         HAB_GRATIS
#define GRA_LANZAR_ASESINOS         HAB_GRATIS
#define GRA_EXPERTISE_ASESINOS      HAB_GRATIS
#define GRA_ENGANYAR_ASESINOS       HAB_GRATIS
#define GRA_MASDANYO_ASESINOS       HAB_GRATIS
#define GRA_FINTAR_ASESINOS         HAB_GRATIS
#define GRA_REFLEXES_ASESINOS       HAB_GRATIS
#define GRA_DO_VENENO_ASESINOS      HAB_GRATIS
#define GRA_ENVENENAR_ASESINOS      HAB_GRATIS
#define GRA_CUTTHROAT_ASESINOS      HAB_GRATIS
#define GRA_PARADA_ASESINOS         HAB_GRATIS
#define GRA_STUN_ASESINOS           HAB_GRATIS
#define GRA_FINTA_MEJORADA_ASESINOS HAB_GRATIS

#define HAB_ASESINOS ({ HAB_CUCHILLO, HAB_ESGRIMA, HAB_ACUCHILLAR, HAB_ESCONDERSE, \
	          HAB_ESQUIVAR, HAB_SIGILO, HAB_XARMAS, HAB_LANZAR, \
            HAB_EXPERTISE, HAB_ENGANYAR, HAB_MASDANYO, HAB_FINTAR, \
            HAB_REFLEXES, HAB_DO_VENENO, HAB_ENVENENAR, HAB_CUTTHROAT, \
            HAB_PARADA, HAB_STUN, HAB_FINTA_MEJORADA })
#define NIV_ASESINOS ({ NIV_CUCHILLO_ASESINOS, NIV_ESGRIMA_ASESINOS, NIV_ACUCHILLAR_ASESINOS, NIV_ESCONDERSE_ASESINOS, \
	          NIV_ESQUIVAR_ASESINOS, NIV_SIGILO_ASESINOS, NIV_XARMAS_ASESINOS, NIV_LANZAR_ASESINOS, \
            NIV_EXPERTISE_ASESINOS, NIV_ENGANYAR_ASESINOS, NIV_MASDANYO_ASESINOS, NIV_FINTAR_ASESINOS, \
            NIV_REFLEXES_ASESINOS, NIV_DO_VENENO_ASESINOS, NIV_ENVENENAR_ASESINOS, NIV_CUTTHROAT_ASESINOS, \
            NIV_PARADA_ASESINOS, NIV_STUN_ASESINOS, NIV_FINTA_MEJORADA_ASESINOS })
#define MAX_ASESINOS ({ MAX_CUCHILLO_ASESINOS, MAX_ESGRIMA_ASESINOS, MAX_ACUCHILLAR_ASESINOS, MAX_ESCONDERSE_ASESINOS, \
	          MAX_ESQUIVAR_ASESINOS, MAX_SIGILO_ASESINOS, MAX_XARMAS_ASESINOS, MAX_LANZAR_ASESINOS, \
            MAX_EXPERTISE_ASESINOS, MAX_ENGANYAR_ASESINOS, MAX_MASDANYO_ASESINOS, MAX_FINTAR_ASESINOS, \
            MAX_REFLEXES_ASESINOS, MAX_DO_VENENO_ASESINOS, MAX_ENVENENAR_ASESINOS, MAX_CUTTHROAT_ASESINOS, \
            MAX_PARADA_ASESINOS, MAX_STUN_ASESINOS, MAX_FINTA_MEJORADA_ASESINOS })
#define GRA_ASESINOS ({ GRA_CUCHILLO_ASESINOS, GRA_ESGRIMA_ASESINOS, GRA_ACUCHILLAR_ASESINOS, GRA_ESCONDERSE_ASESINOS, \
	          GRA_ESQUIVAR_ASESINOS, GRA_SIGILO_ASESINOS, GRA_XARMAS_ASESINOS, GRA_LANZAR_ASESINOS, \
            GRA_EXPERTISE_ASESINOS, GRA_ENGANYAR_ASESINOS, GRA_MASDANYO_ASESINOS, GRA_FINTAR_ASESINOS, \
            GRA_REFLEXES_ASESINOS, GRA_DO_VENENO_ASESINOS, GRA_ENVENENAR_ASESINOS, GRA_CUTTHROAT_ASESINOS, \
            GRA_PARADA_ASESINOS, GRA_STUN_ASESINOS, GRA_FINTA_MEJORADA_ASESINOS })

//**********************||
// HABILIDADES CLERIGOS ||
//**********************||
#define NIV_VARA_CLERIGOS           5
#define NIV_MAZA_CLERIGOS           5
#define NIV_CADENA_CLERIGOS         5
#define NIV_MANGUAL_CLERIGOS        5
#define NIV_MEDITACION_CLERIGOS     1
#define NIV_MEMORIZAR_CLERIGOS      1
#define NIV_RUNAS_CLERIGOS          1
#define NIV_ESCRIBIR_RUNAS_CLERIGOS 10
#define NIV_PARADA_CLERIGOS         25

#define MAX_VARA_CLERIGOS           100
#define MAX_MAZA_CLERIGOS           100
#define MAX_CADENA_CLERIGOS         100
#define MAX_MANGUAL_CLERIGOS        100
#define MAX_MEDITACION_CLERIGOS     100
#define MAX_MEMORIZAR_CLERIGOS      100
#define MAX_RUNAS_CLERIGOS          100
#define MAX_ESCRIBIR_RUNAS_CLERIGOS 100
#define MAX_PARADA_CLERIGOS         100

#define GRA_VARA_CLERIGOS           HAB_GRATIS
#define GRA_MAZA_CLERIGOS           HAB_GRATIS
#define GRA_CADENA_CLERIGOS         HAB_GRATIS
#define GRA_MANGUAL_CLERIGOS        HAB_GRATIS
#define GRA_MEDITACION_CLERIGOS     HAB_GRATIS
#define GRA_MEMORIZAR_CLERIGOS      HAB_GRATIS
#define GRA_RUNAS_CLERIGOS          HAB_GRATIS
#define GRA_ESCRIBIR_RUNAS_CLERIGOS HAB_GRATIS
#define GRA_PARADA_CLERIGOS         HAB_GRATIS

#define HAB_CLERIGOS ({ HAB_VARA, HAB_MAZA, HAB_CADENA, HAB_MANGUAL, \
            HAB_PARADA, HAB_MEDITACION, HAB_ESCRIBIR_RUNAS, \
            HAB_MEMORIZAR, HAB_RUNAS })
#define NIV_CLERIGOS ({ NIV_VARA_CLERIGOS, NIV_MAZA_CLERIGOS, NIV_CADENA_CLERIGOS, NIV_MANGUAL_CLERIGOS, \
            NIV_PARADA_CLERIGOS, NIV_MEDITACION_CLERIGOS, NIV_ESCRIBIR_RUNAS_CLERIGOS, \
            NIV_MEMORIZAR_CLERIGOS, NIV_RUNAS_CLERIGOS })
#define MAX_CLERIGOS ({ MAX_VARA_CLERIGOS, MAX_MAZA_CLERIGOS, MAX_CADENA_CLERIGOS, MAX_MANGUAL_CLERIGOS, \
            MAX_PARADA_CLERIGOS, MAX_MEDITACION_CLERIGOS, MAX_ESCRIBIR_RUNAS_CLERIGOS, \
            MAX_MEMORIZAR_CLERIGOS, MAX_RUNAS_CLERIGOS })
#define GRA_CLERIGOS ({ GRA_VARA_CLERIGOS, GRA_MAZA_CLERIGOS, GRA_CADENA_CLERIGOS, GRA_MANGUAL_CLERIGOS, \
            GRA_PARADA_CLERIGOS, GRA_MEDITACION_CLERIGOS, GRA_ESCRIBIR_RUNAS_CLERIGOS, \
            GRA_MEMORIZAR_CLERIGOS, GRA_RUNAS_CLERIGOS })

//***********************||
// HABILIDADES NINGUNO   ||
//***********************||
#define NIV_VARA_NINGUNO        5
#define NIV_CUCHILLO_NINGUNO    5
#define NIV_LANZA_NINGUNO       5
#define NIV_ALABARDA_NINGUNO    5
#define NIV_HACHA_NINGUNO       5
#define NIV_CADENA_NINGUNO      5
#define NIV_MAZA_NINGUNO        5
#define NIV_LATIGO_NINGUNO      5
#define NIV_MANGUAL_NINGUNO     5
#define NIV_ESGRIMA_NINGUNO     5
#define NIV_ESPADA_NINGUNO      5
#define NIV_MANOPLA_NINGUNO     5
#define NIV_SINARMAS_NINGUNO    5
#define NIV_ESCUDO_NINGUNO      25
#define NIV_EXPERTISE_NINGUNO   20
#define NIV_PARADA_NINGUNO      20
#define NIV_MASDANYO_NINGUNO    35
#define NIV_ESQUIVAR_NINGUNO    15
#define NIV_REFLEXES_NINGUNO    25
#define NIV_GUERRERO_NINGUNO    45
#define NIV_CRITICO_NINGUNO     55

#define MAX_VARA_NINGUNO        100
#define MAX_CUCHILLO_NINGUNO    100
#define MAX_LANZA_NINGUNO       100
#define MAX_ALABARDA_NINGUNO    100
#define MAX_HACHA_NINGUNO       100
#define MAX_CADENA_NINGUNO      100
#define MAX_MAZA_NINGUNO        100
#define MAX_LATIGO_NINGUNO      100
#define MAX_MANGUAL_NINGUNO     100
#define MAX_ESGRIMA_NINGUNO     100
#define MAX_ESPADA_NINGUNO      100
#define MAX_MANOPLA_NINGUNO     100
#define MAX_SINARMAS_NINGUNO    100
#define MAX_ESCUDO_NINGUNO      100
#define MAX_EXPERTISE_NINGUNO   100
#define MAX_PARADA_NINGUNO      100
#define MAX_MASDANYO_NINGUNO    100
#define MAX_ESQUIVAR_NINGUNO    100
#define MAX_REFLEXES_NINGUNO    100
#define MAX_GUERRERO_NINGUNO    100
#define MAX_CRITICO_NINGUNO     100


#define GRA_VARA_NINGUNO        HAB_GRATIS
#define GRA_CUCHILLO_NINGUNO    HAB_GRATIS
#define GRA_LANZA_NINGUNO       HAB_GRATIS
#define GRA_ALABARDA_NINGUNO    HAB_GRATIS
#define GRA_HACHA_NINGUNO       HAB_GRATIS
#define GRA_CADENA_NINGUNO      HAB_GRATIS
#define GRA_MAZA_NINGUNO        HAB_GRATIS
#define GRA_LATIGO_NINGUNO      HAB_GRATIS
#define GRA_MANGUAL_NINGUNO     HAB_GRATIS
#define GRA_ESGRIMA_NINGUNO     HAB_GRATIS
#define GRA_ESPADA_NINGUNO      HAB_GRATIS
#define GRA_MANOPLA_NINGUNO     HAB_GRATIS
#define GRA_SINARMAS_NINGUNO    HAB_GRATIS
#define GRA_ESCUDO_NINGUNO      HAB_GRATIS
#define GRA_EXPERTISE_NINGUNO   HAB_GRATIS
#define GRA_PARADA_NINGUNO      HAB_GRATIS
#define GRA_MASDANYO_NINGUNO    HAB_GRATIS
#define GRA_ESQUIVAR_NINGUNO    HAB_GRATIS
#define GRA_REFLEXES_NINGUNO    HAB_GRATIS
#define GRA_GUERRERO_NINGUNO    HAB_GRATIS
#define GRA_CRITICO_NINGUNO     HAB_GRATIS

#define HAB_NINGUNO    ({ HAB_VARA, HAB_CUCHILLO, HAB_LANZA, \
               HAB_ALABARDA, HAB_HACHA, HAB_CADENA, HAB_MAZA, \
               HAB_LATIGO, HAB_MANGUAL, HAB_ESGRIMA, HAB_ESPADA, \
               HAB_MANOPLA, HAB_SINARMAS, HAB_PARADA, \
               HAB_ESCUDO, HAB_EXPERTISE, HAB_MASDANYO, \
               HAB_ESQUIVAR, HAB_REFLEXES, \
               HAB_GUERRERO, HAB_CRITICO, \
                         })
#define NIV_NINGUNO   ({ NIV_VARA_NINGUNO, NIV_CUCHILLO_NINGUNO, NIV_LANZA_NINGUNO, \
               NIV_ALABARDA_NINGUNO, NIV_HACHA_NINGUNO, NIV_CADENA_NINGUNO, NIV_MAZA_NINGUNO, \
               NIV_LATIGO_NINGUNO, NIV_MANGUAL_NINGUNO, NIV_ESGRIMA_NINGUNO, NIV_ESPADA_NINGUNO, \
               NIV_MANOPLA_NINGUNO, NIV_SINARMAS_NINGUNO, NIV_PARADA_NINGUNO, \
               NIV_ESCUDO_NINGUNO, NIV_EXPERTISE_NINGUNO, NIV_MASDANYO_NINGUNO, \
               NIV_ESQUIVAR_NINGUNO, NIV_REFLEXES_NINGUNO, \
               NIV_GUERRERO_NINGUNO, NIV_CRITICO_NINGUNO, \
                       })
#define MAX_NINGUNO   ({ MAX_VARA_NINGUNO, MAX_CUCHILLO_NINGUNO, MAX_LANZA_NINGUNO, \
               MAX_ALABARDA_NINGUNO, MAX_HACHA_NINGUNO, MAX_CADENA_NINGUNO, MAX_MAZA_NINGUNO, \
               MAX_LATIGO_NINGUNO, MAX_MANGUAL_NINGUNO, MAX_ESGRIMA_NINGUNO, MAX_ESPADA_NINGUNO, \
               MAX_MANOPLA_NINGUNO, MAX_SINARMAS_NINGUNO, MAX_PARADA_NINGUNO, \
               MAX_ESCUDO_NINGUNO, MAX_EXPERTISE_NINGUNO, MAX_MASDANYO_NINGUNO, \
               MAX_ESQUIVAR_NINGUNO, MAX_REFLEXES_NINGUNO, \
               MAX_GUERRERO_NINGUNO, MAX_CRITICO_NINGUNO, \
                       })
#define GRA_NINGUNO   ({ GRA_VARA_NINGUNO, GRA_CUCHILLO_NINGUNO, GRA_LANZA_NINGUNO, \
               GRA_ALABARDA_NINGUNO, GRA_HACHA_NINGUNO, GRA_CADENA_NINGUNO, GRA_MAZA_NINGUNO, \
               GRA_LATIGO_NINGUNO, GRA_MANGUAL_NINGUNO, GRA_ESGRIMA_NINGUNO, GRA_ESPADA_NINGUNO, \
               GRA_MANOPLA_NINGUNO, GRA_SINARMAS_NINGUNO, GRA_PARADA_NINGUNO, \
               GRA_ESCUDO_NINGUNO, GRA_EXPERTISE_NINGUNO, GRA_MASDANYO_NINGUNO, \
               GRA_ESQUIVAR_NINGUNO, GRA_REFLEXES_NINGUNO, \
               GRA_GUERRERO_NINGUNO, GRA_CRITICO_NINGUNO, \
                       })

//***********************||
// HABILIDADES AVENTUREROS ||
//***********************||
#define NIV_CUCHILLO_AVENTUREROS    1
#define NIV_CAYADO_AVENTUREROS 1
#define NIV_DAGA_AVENTUREROS    2
#define NIV_LEÑA_AVENTUREROS 2
#define NIV_HOGUERAS_AVENTUREROS 3
#define NIV_PESCAR_AVENTUREROS    4
#define NIV_COCINAR_AVENTUREROS    5
#define NIV_IMPROVISADA_AVENTUREROS 6
#define NIV_ESCALAR_AVENTUREROS    7
#define NIV_SALTAR_AVENTUREROS    8
#define NIV_COMERCIAR_AVENTUREROS    9
#define NIV_LANZAR_AVENTUREROS    10
#define NIV_NADAR_AVENTUREROS    11
#define NIV_ESPADA_AVENTUREROS      13
#define NIV_ESPADA_CORTA_AVENTUREROS      13
#define NIV_LANZA_AVENTUREROS    13
#define NIV_HACHA_AVENTUREROS    13
#define NIV_CADENA_AVENTUREROS    13
#define NIV_MAZA_AVENTUREROS    13
#define NIV_MANGUAL_AVENTUREROS    13
#define NIV_CIMITARRA_AVENTUREROS 13
#define NIV_JABALINA_AVENTUREROS 13
#define NIV_DESCUARTIZAR_AVENTUREROS 14
#define NIV_ESQUILAR_AVENTUREROS 16
#define NIV_ESQUIVAR_AVENTUREROS    17
#define NIV_DESOLLAR_AVENTUREROS 18
#define NIV_VENDAJE_AVENTUREROS    20
#define NIV_ATISBAR_AVENTUREROS 21
#define NIV_INSPECCIONAR_AVENTUREROS 22
#define NIV_PARADA_AVENTUREROS    23
#define NIV_IDPLANTAS_AVENTUREROS 24
#define NIV_REPARAR_AVENTUREROS    25
#define NIV_IDENTIFICAR_AVENTUREROS 26
#define NIV_SINARMAS_AVENTUREROS 27
#define NIV_ARBOLES_AVENTUREROS 28
#define NIV_ROBAR_AVENTUREROS    29
#define NIV_ZANCADILLEAR_AVENTUREROS 30
#define NIV_BALSAMO_AVENTUREROS 31
#define NIV_TALAR_AVENTUREROS 33
#define NIV_MADERA_AVENTUREROS 40
#define NIV_ESCUDO_AVENTUREROS 45

#define MAX_CAYADO_AVENTUREROS    100
#define MAX_CUCHILLO_AVENTUREROS    90
#define MAX_DAGA_AVENTUREROS    90
#define MAX_LEÑA_AVENTUREROS 100
#define MAX_HOGUERAS_AVENTUREROS 100
#define MAX_PESCAR_AVENTUREROS    100
#define MAX_COCINAR_AVENTUREROS    70
#define MAX_IMPROVISADA_AVENTUREROS 90
#define MAX_ESCALAR_AVENTUREROS    100
#define MAX_SALTAR_AVENTUREROS    90
#define MAX_COMERCIAR_AVENTUREROS    100
#define MAX_LANZAR_AVENTUREROS    80 // quizá para hobbits a 100
#define MAX_NADAR_AVENTUREROS    100
#define MAX_ESPADA_AVENTUREROS      60
#define MAX_ESPADA_CORTA_AVENTUREROS      90
#define MAX_LANZA_AVENTUREROS    90
#define MAX_HACHA_AVENTUREROS    90
#define MAX_CADENA_AVENTUREROS    60
#define MAX_MAZA_AVENTUREROS    60
#define MAX_MANGUAL_AVENTUREROS    60
#define MAX_CIMITARRA_AVENTUREROS      70
#define MAX_JABALINA_AVENTUREROS 90
#define MAX_DESCUARTIZAR_AVENTUREROS 90
#define MAX_ESQUILAR_AVENTUREROS 90
#define MAX_ESQUIVAR_AVENTUREROS    70 // hobbits 90 o 100
#define MAX_DESOLLAR_AVENTUREROS 90
#define MAX_VENDAJE_AVENTUREROS    70
#define MAX_ATISBAR_AVENTUREROS 100
#define MAX_INSPECCIONAR_AVENTUREROS 70
#define MAX_PARADA_AVENTUREROS    70
#define MAX_IDPLANTAS_AVENTUREROS 70
#define MAX_REPARAR_AVENTUREROS    70
#define MAX_IDENTIFICAR_AVENTUREROS 50
#define MAX_SINARMAS_AVENTUREROS    70
#define MAX_ARBOLES_AVENTUREROS 100
#define MAX_ROBAR_AVENTUREROS    100
#define MAX_ZANCADILLEAR_AVENTUREROS 90
#define MAX_BALSAMO_AVENTUREROS 70
#define MAX_TALAR_AVENTUREROS 90
#define MAX_MADERA_AVENTUREROS 90
#define MAX_ESCUDO_AVENTUREROS 70

#define GRA_CAYADO_AVENTUREROS    HAB_GRATIS
#define GRA_CUCHILLO_AVENTUREROS    HAB_GRATIS
#define GRA_DAGA_AVENTUREROS    HAB_GRATIS
#define GRA_LEÑA_AVENTUREROS HAB_GRATIS
#define GRA_HOGUERAS_AVENTUREROS HAB_GRATIS
#define GRA_PESCAR_AVENTUREROS    HAB_GRATIS
#define GRA_COCINAR_AVENTUREROS    HAB_GRATIS
#define GRA_IMPROVISADA_AVENTUREROS      HAB_GRATIS
#define GRA_ESCALAR_AVENTUREROS      HAB_GRATIS
#define GRA_SALTAR_AVENTUREROS      HAB_GRATIS
#define GRA_COMERCIAR_AVENTUREROS      HAB_GRATIS
#define GRA_LANZAR_AVENTUREROS      HAB_GRATIS
#define GRA_NADAR_AVENTUREROS      HAB_GRATIS
#define GRA_ESPADA_AVENTUREROS      HAB_GRATIS
#define GRA_ESPADA_CORTA_AVENTUREROS      HAB_GRATIS
#define GRA_LANZA_AVENTUREROS      HAB_GRATIS
#define GRA_HACHA_AVENTUREROS      HAB_GRATIS
#define GRA_CADENA_AVENTUREROS      HAB_GRATIS
#define GRA_MAZA_AVENTUREROS      HAB_GRATIS
#define GRA_MANGUAL_AVENTUREROS      HAB_GRATIS
#define GRA_CIMITARRA_AVENTUREROS      HAB_GRATIS
#define GRA_JABALINA_AVENTUREROS       HAB_GRATIS
#define GRA_DESCUARTIZAR_AVENTUREROS HAB_GRATIS
#define GRA_ESQUILAR_AVENTUREROS HAB_GRATIS
#define GRA_ESQUIVAR_AVENTUREROS      HAB_GRATIS
#define GRA_DESOLLAR_AVENTUREROS HAB_GRATIS
#define GRA_VENDAJE_AVENTUREROS      HAB_GRATIS
#define GRA_ATISBAR_AVENTUREROS HAB_GRATIS
#define GRA_INSPECCIONAR_AVENTUREROS HAB_GRATIS
#define GRA_PARADA_AVENTUREROS      HAB_GRATIS
#define GRA_IDPLANTAS_AVENTUREROS      HAB_GRATIS
#define GRA_REPARAR_AVENTUREROS      HAB_GRATIS
#define GRA_IDENTIFICAR_AVENTUREROS HAB_GRATIS
#define GRA_SINARMAS_AVENTUREROS    HAB_GRATIS
#define GRA_ARBOLES_AVENTUREROS HAB_GRATIS
#define GRA_ROBAR_AVENTUREROS HAB_GRATIS
#define GRA_ZANCADILLEAR_AVENTUREROS      HAB_GRATIS
#define GRA_BALSAMO_AVENTUREROS      HAB_GRATIS
#define GRA_TALAR_AVENTUREROS HAB_GRATIS
#define GRA_MADERA_AVENTUREROS HAB_GRATIS
#define GRA_ESCUDO_AVENTUREROS      HAB_GRATIS

#define HAB_AVENTUREROS    ({ HAB_CAYADO, HAB_CUCHILLO, HAB_DAGA, HAB_LEÑA, HAB_HOGUERAS, HAB_PESCAR, HAB_COCINAR, \
    HAB_IMPROVISADA, HAB_ESCALAR, HAB_SALTAR, HAB_COMERCIAR, HAB_LANZAR, HAB_NADAR, HAB_ESPADA, HAB_ESPADA_CORTA, HAB_LANZA, \
    HAB_HACHA, HAB_CADENA, HAB_MAZA, HAB_MANGUAL, HAB_CIMITARRA, HAB_JABALINA, HAB_DESCUARTIZAR, HAB_ESQUILAR, HAB_ESQUIVAR, \
    HAB_DESOLLAR, HAB_VENDAJE, HAB_ATISBAR, HAB_INSPECCIONAR, HAB_PARADA, HAB_IDPLANTAS, \
    HAB_REPARAR, HAB_IDENTIFICAR, HAB_SINARMAS, HAB_ARBOLES, HAB_ROBAR, HAB_ZANCADILLEAR, HAB_BALSAMO, \
    HAB_TALAR, HAB_MADERA, HAB_ESCUDO, \
                                 })

#define NIV_AVENTUREROS ({ NIV_CAYADO_AVENTUREROS, NIV_CUCHILLO_AVENTUREROS, NIV_DAGA_AVENTUREROS, NIV_LEÑA_AVENTUREROS, NIV_HOGUERAS_AVENTUREROS, \
    NIV_PESCAR_AVENTUREROS, NIV_COCINAR_AVENTUREROS, NIV_IMPROVISADA_AVENTUREROS, \
     NIV_ESCALAR_AVENTUREROS, NIV_SALTAR_AVENTUREROS, NIV_COMERCIAR_AVENTUREROS, NIV_LANZAR_AVENTUREROS, NIV_NADAR_AVENTUREROS, NIV_ESPADA_AVENTUREROS, \
     NIV_ESPADA_CORTA_AVENTUREROS, NIV_LANZA_AVENTUREROS, NIV_HACHA_AVENTUREROS, NIV_CADENA_AVENTUREROS, \
     NIV_MAZA_AVENTUREROS, NIV_MANGUAL_AVENTUREROS, NIV_CIMITARRA_AVENTUREROS, NIV_JABALINA_AVENTUREROS, \
NIV_DESCUARTIZAR_AVENTUREROS, NIV_ESQUILAR_AVENTUREROS, NIV_ESQUIVAR_AVENTUREROS, NIV_DESOLLAR_AVENTUREROS, \
NIV_VENDAJE_AVENTUREROS, NIV_ATISBAR_AVENTUREROS, NIV_INSPECCIONAR_AVENTUREROS, NIV_PARADA_AVENTUREROS, \
NIV_IDPLANTAS_AVENTUREROS, NIV_REPARAR_AVENTUREROS, NIV_IDENTIFICAR_AVENTUREROS, \
NIV_SINARMAS_AVENTUREROS, NIV_ARBOLES_AVENTUREROS, NIV_ROBAR_AVENTUREROS, NIV_ZANCADILLEAR_AVENTUREROS, NIV_BALSAMO_AVENTUREROS, \
     NIV_TALAR_AVENTUREROS, NIV_MADERA_AVENTUREROS, NIV_ESCUDO_AVENTUREROS,\
                                        })

#define MAX_AVENTUREROS ({ MAX_CAYADO_AVENTUREROS, MAX_CUCHILLO_AVENTUREROS, MAX_DAGA_AVENTUREROS, \
MAX_LEÑA_AVENTUREROS, MAX_HOGUERAS_AVENTUREROS,    MAX_PESCAR_AVENTUREROS, MAX_COCINAR_AVENTUREROS, \
MAX_IMPROVISADA_AVENTUREROS, MAX_ESCALAR_AVENTUREROS, MAX_SALTAR_AVENTUREROS, MAX_COMERCIAR_AVENTUREROS, \
MAX_LANZAR_AVENTUREROS, MAX_NADAR_AVENTUREROS, MAX_ESPADA_AVENTUREROS, MAX_ESPADA_CORTA_AVENTUREROS, \
MAX_LANZA_AVENTUREROS, MAX_HACHA_AVENTUREROS, MAX_CADENA_AVENTUREROS, \
     MAX_MAZA_AVENTUREROS, MAX_MANGUAL_AVENTUREROS,  MAX_CIMITARRA_AVENTUREROS, MAX_JABALINA_AVENTUREROS, \
     MAX_DESCUARTIZAR_AVENTUREROS, MAX_ESQUILAR_AVENTUREROS, MAX_ESQUIVAR_AVENTUREROS, MAX_DESOLLAR_AVENTUREROS, \
      MAX_VENDAJE_AVENTUREROS, MAX_ATISBAR_AVENTUREROS, MAX_INSPECCIONAR_AVENTUREROS, MAX_PARADA_AVENTUREROS, MAX_IDPLANTAS_AVENTUREROS, MAX_REPARAR_AVENTUREROS, \
     MAX_IDPLANTAS_AVENTUREROS,  MAX_SINARMAS_AVENTUREROS, MAX_ARBOLES_AVENTUREROS,  MAX_ROBAR_AVENTUREROS, MAX_ZANCADILLEAR_AVENTUREROS, MAX_BALSAMO_AVENTUREROS, \
      MAX_TALAR_AVENTUREROS, MAX_MADERA_AVENTUREROS,MAX_ESCUDO_AVENTUREROS, \
                                        })
#define GRA_AVENTUREROS ({ GRA_CAYADO_AVENTUREROS, GRA_CUCHILLO_AVENTUREROS, GRA_DAGA_AVENTUREROS, \
    GRA_LEÑA_AVENTUREROS, GRA_HOGUERAS_AVENTUREROS, GRA_PESCAR_AVENTUREROS, GRA_COCINAR_AVENTUREROS, \
    GRA_IMPROVISADA_AVENTUREROS, GRA_ESCALAR_AVENTUREROS, GRA_SALTAR_AVENTUREROS, GRA_COMERCIAR_AVENTUREROS, \
    GRA_LANZAR_AVENTUREROS, GRA_NADAR_AVENTUREROS, GRA_ESPADA_AVENTUREROS, GRA_ESPADA_CORTA_AVENTUREROS, \
    GRA_LANZA_AVENTUREROS, GRA_HACHA_AVENTUREROS, GRA_CADENA_AVENTUREROS, GRA_MAZA_AVENTUREROS, \
    GRA_MANGUAL_AVENTUREROS,  GRA_CIMITARRA_AVENTUREROS, GRA_JABALINA_AVENTUREROS, \
     GRA_DESCUARTIZAR_AVENTUREROS, GRA_ESQUILAR_AVENTUREROS, GRA_ESQUIVAR_AVENTUREROS, GRA_DESOLLAR_AVENTUREROS, \
     GRA_VENDAJE_AVENTUREROS, GRA_ATISBAR_AVENTUREROS, GRA_INSPECCIONAR_AVENTUREROS, \
     GRA_PARADA_AVENTUREROS, GRA_IDPLANTAS_AVENTUREROS, GRA_REPARAR_AVENTUREROS, \
     GRA_IDENTIFICAR_AVENTUREROS, GRA_SINARMAS_AVENTUREROS, GRA_ARBOLES_AVENTUREROS, GRA_ROBAR_AVENTUREROS, \
     GRA_ZANCADILLEAR_AVENTUREROS, GRA_BALSAMO_AVENTUREROS, GRA_TALAR_AVENTUREROS, \
     GRA_MADERA_AVENTUREROS, GRA_ESCUDO_AVENTUREROS,\
                         })
//***********************||
// HABILIDADES EXPLORADORES||
//***********************||
#define NIV_CUCHILLO_EXPLORADORES    1
#define NIV_ESPADA_EXPLORADORES      20
#define NIV_SINARMAS_EXPLORADORES    1

#define MAX_CUCHILLO_EXPLORADORES    100
#define MAX_ESPADA_EXPLORADORES      100
#define MAX_SINARMAS_EXPLORADORES    100

#define GRA_CUCHILLO_EXPLORADORES    HAB_GRATIS
#define GRA_ESPADA_EXPLORADORES      HAB_GRATIS
#define GRA_SINARMAS_EXPLORADORES    HAB_GRATIS

#define HAB_EXPLORADORES    ({ HAB_CUCHILLO, HAB_ESPADA, \
               HAB_SINARMAS,  \
                         })
#define NIV_EXPLORADORES ({ NIV_CUCHILLO_EXPLORADORES, NIV_ESPADA_EXPLORADORES, \
               NIV_SINARMAS_EXPLORADORES, \
                         })
#define MAX_EXPLORADORES ({ MAX_CUCHILLO_EXPLORADORES, MAX_ESPADA_EXPLORADORES, \
               MAX_SINARMAS_EXPLORADORES, \
                         })
#define GRA_EXPLORADORES ({ GRA_CUCHILLO_EXPLORADORES, GRA_ESPADA_EXPLORADORES, \
               GRA_SINARMAS_EXPLORADORES, \
                         })

//**********************||


#define HAB_GREMIOS     HAB_CLERIGOS+HAB_KISALAS+HAB_GUERREROS+HAB_CONJURADORES+HAB_GUARDABOSQUES+HAB_HECHICEROS+HAB_ASESINOS+HAB_NINGUNO+HAB_AVENTUREROS+HAB_EXPLORADORES

#define HABILIDADES  ([ GC_KISALAS:       HAB_KISALAS,\
                        GC_GUERREROS:     HAB_GUERREROS,\
                        GC_CONJURADORES:  HAB_CONJURADORES,\
                        GC_GUARDABOSQUES: HAB_GUARDABOSQUES,\
                        GC_HECHICEROS:    HAB_HECHICEROS,\
                        GC_ASESINOS:      HAB_ASESINOS,\
                        GC_NINGUNO:       HAB_NINGUNO,\
                        GC_AVENTUREROS:   HAB_AVENTUREROS,\
                            GC_EXPLORADORES:   HAB_EXPLORADORES,\
                     ])

#define HAB_MAP_NIV    0 //nivel
#define HAB_MAP_MAX    1 //maximo
#define HAB_MAP_GRA    2 //gratis

#define NIV_HAB_KISALAS         mkmapping(HAB_KISALAS,      NIV_KISALAS,      MAX_KISALAS,      GRA_KISALAS      )
#define NIV_HAB_GUERREROS       mkmapping(HAB_GUERREROS,    NIV_GUERREROS,    MAX_GUERREROS,    GRA_GUERREROS    )
#define NIV_HAB_CONJURADORES    mkmapping(HAB_CONJURADORES, NIV_CONJURADORES, MAX_CONJURADORES, GRA_CONJURADORES )
#define NIV_HAB_GUARDABOSQUES   mkmapping(HAB_GUARDABOSQUES,NIV_GUARDABOSQUES,MAX_GUARDABOSQUES,GRA_GUARDABOSQUES)
#define NIV_HAB_HECHICEROS      mkmapping(HAB_HECHICEROS,   NIV_HECHICEROS,   MAX_HECHICEROS,   GRA_HECHICEROS   )
#define NIV_HAB_ASESINOS        mkmapping(HAB_ASESINOS,     NIV_ASESINOS,     MAX_ASESINOS,     GRA_ASESINOS     )

#define HAB_MAP_AVENTUREROS     mkmapping(HAB_AVENTUREROS,  NIV_AVENTUREROS,  MAX_AVENTUREROS,  GRA_AVENTUREROS  )
#define HAB_MAP_EXPLORADORES     mkmapping(HAB_EXPLORADORES,  NIV_EXPLORADORES,  MAX_EXPLORADORES,  GRA_EXPLORADORES  )
#define HAB_MAP_KISALAS         NIV_HAB_KISALAS
#define HAB_MAP_GUERREROS       NIV_HAB_GUERREROS
#define HAB_MAP_CONJURADORES    NIV_HAB_CONJURADORES
#define HAB_MAP_GUARDABOSQUES   NIV_HAB_GUARDABOSQUES
#define HAB_MAP_HECHICEROS      NIV_HAB_HECHICEROS
#define HAB_MAP_ASESINOS        NIV_HAB_ASESINOS
//clases de pnj
#define HAB_MAP_EXPERTO         (HAB_MAP_HECHICEROS+HAB_MAP_GUERREROS)
#define HAB_MAP_LUCHADOR        HAB_MAP_GUERREROS
#define HAB_MAP_NINGUNO         mkmapping(HAB_NINGUNO,      NIV_NINGUNO,      MAX_NINGUNO,      GRA_NINGUNO      )
#define HAB_MAP_MAGO            HAB_MAP_HECHICEROS
#define HAB_MAP_TORPE           HAB_MAP_AVENTUREROS
//fin clases de pnj

#define HAB_MAP ([  GC_KISALAS:         HAB_MAP_KISALAS,    \
                    GC_GUERREROS:       HAB_MAP_GUERREROS,    \
                    GC_CONJURADORES:    HAB_MAP_CONJURADORES,    \
                    GC_GUARDABOSQUES:   HAB_MAP_GUARDABOSQUES,    \
                    GC_HECHICEROS:      HAB_MAP_HECHICEROS,    \
                    GC_ASESINOS:        HAB_MAP_ASESINOS,    \
                    GC_AVENTUREROS:     HAB_MAP_AVENTUREROS,    \
                        GC_EXPLORADORES:     HAB_MAP_EXPLORADORES,    \
                    GC_EXPERTO:         HAB_MAP_EXPERTO,    \//pnj
                    GC_LUCHADOR:        HAB_MAP_LUCHADOR,    \//pnj
                    GC_NINGUNO:         HAB_MAP_NINGUNO,    \//pnj
                    GC_MAGO:            HAB_MAP_MAGO,        \//pnj
                    GC_TORPE:           HAB_MAP_TORPE,        \//pnj
                ])


#endif /* _SKILLS_H */
