/*
DESCRIPCION : puerta de una ciudad
FICHERO     : puerta_ciudad.h
MODIFICACION: 25-02-00 [Angor@Simauria] Creacion
              15-08-01 [Angor@Simauria] Modificacion
*/

//tipos de habitaciones

#define PC_ESCALERA_PLANTA_BAJA 1
#define PC_ESCALERA_PLANTA_0_1 2
#define PC_ESCALERA_PLANTA_1 3

#define PC_PLANTA_1_CENTRO_BALCON 4
#define PC_PLANTA_1_CENTRO_AGUJERO 5
#define PC_PLANTA_1_CENTRO_MURO 6
#define PC_PLANTA_1_TORRE_PUERTA 7

#define PC_PLANTA_1_TORRE_CENTRO 8
#define PC_PLANTA_1_TORRE_CHIMENEA 9
#define PC_PLANTA_1_TORRE_ARMAS 10
#define PC_PLANTA_1_TORRE_LITERAS 11
#define PC_PLANTA_1_TORRE_ESCALERA 12

#define PC_PLANTA_0_PUERTA 13
#define PC_PLANTA_0_CENTRO_1 14
#define PC_PLANTA_0_CENTRO_2 15
#define PC_PLANTA_0_CAJAS 16
#define PC_PLANTA_0_BARRILES 17
#define PC_PLANTA_0_LENYA 18
#define PC_PLANTA_0_ESCALERA 19

#define PC_PLANTA_0_1_ESCALERA 20

